import os
iconDir = os.path.join(os.path.dirname(__file__), "icon")
nkDir   = os.path.join(os.path.dirname(__file__), "nk")

toolbar = nuke.toolbar("Nodes")
zqMenu  = toolbar.addMenu("zqb0x", icon=os.path.join(iconDir, "zqicon.png"))

zqMenu.addCommand("zq Chromatic Aberration Artistic",             "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqchromaticaberrationartistic.nk")),             icon=os.path.join(iconDir, "zqicon.png"))
zqMenu.addCommand("zq Chromatic Aberration Nerdy",                "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqchromaticaberrationnerdy.nk")),                icon=os.path.join(iconDir, "zqicon.png"))
zqMenu.addCommand("zq Depth Blur Blink",                          "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqdepthblurblink.nk")),                          icon=os.path.join(iconDir, "zqicon.png"))
zqMenu.addCommand("zq Depth Blur Iterative",                      "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqdepthbluriterative.nk")),                      icon=os.path.join(iconDir, "zqicon.png"))
zqMenu.addCommand("zq Depth Bokeh Generator",                     "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqdepthbokehgenerator.nk")),                     icon=os.path.join(iconDir, "zqicon.png"))
zqMenu.addCommand("zq Depth Remap",                               "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqdepthremap.nk")),                              icon=os.path.join(iconDir, "zqicon.png"))
zqMenu.addCommand("zq Detail Normals",                            "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqdetailnormals.nk")),                           icon=os.path.join(iconDir, "zqicon.png"))
zqMenu.addCommand("zq Edge Distort",                              "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqedgedistort.nk")),                             icon=os.path.join(iconDir, "zqicon.png"))
zqMenu.addCommand("zq Fake Crypto",                               "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqfakecrypto.nk")),                              icon=os.path.join(iconDir, "zqicon.png"))
zqMenu.addCommand("zq Fake Motion",                               "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqfakemotion.nk")),                              icon=os.path.join(iconDir, "zqicon.png"))
zqMenu.addCommand("zq Grain",                                     "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqgrain.nk")),                                   icon=os.path.join(iconDir, "zqicon.png"))
zqMenu.addCommand("zq Halation",                                  "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqhalation.nk")),                                icon=os.path.join(iconDir, "zqicon.png"))
zqMenu.addCommand("zq Lightwrap Luma",                            "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqlightwrapluma.nk")),                           icon=os.path.join(iconDir, "zqicon.png"))
zqMenu.addCommand("zq Lightwrap Unified",                         "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqlightwrapunified.nk")),                        icon=os.path.join(iconDir, "zqicon.png"))
zqMenu.addCommand("zq NAN iNF",                                   "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqnaninf.nk")),                                  icon=os.path.join(iconDir, "zqicon.png"))
zqMenu.addCommand("zq Normal Deband",                             "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqnormaldeband.nk")),                            icon=os.path.join(iconDir, "zqicon.png"))
zqMenu.addCommand("zq Normal Falloff",                            "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqnormalfalloff.nk")),                           icon=os.path.join(iconDir, "zqicon.png"))
zqMenu.addCommand("zq Position Falloff",                          "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqpositionfalloff.nk")),                         icon=os.path.join(iconDir, "zqicon.png"))
zqMenu.addCommand("zq Quasi Occlusion",                           "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqquasiocclusion.nk")),                          icon=os.path.join(iconDir, "zqicon.png"))
zqMenu.addCommand("zq Triplanar",                                 "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqtriplanar.nk")),                               icon=os.path.join(iconDir, "zqicon.png"))
zqMenu.addCommand("zq Vanishing Point Guide",                     "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqvanishingpointguide.nk")),                     icon=os.path.join(iconDir, "zqicon.png"))
zqMenu.addCommand("zq Vignette",                                  "nuke.nodePaste(r'{}')".format(os.path.join(nkDir, "zqvignette.nk")),                                icon=os.path.join(iconDir, "zqicon.png"))